# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Sameera Perera
tagline:             'Ramblings of a Clean Code Junkie'
description:         'A reserved <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme that places the utmost gravity on content with a hidden drawer. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:                 https://sameera.github.io
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Sameera Perera
  url:               https://twitter.com/codoxide

# Custom vars
version:             1.0.0
